sudo: false
dist: xenial
language: ruby
rvm:
  - 2.6.5
branches:
  only:
    - master
cache: bundler
before_install:
  - 'echo "gem: --no-ri --no-rdoc --no-document" > ~/.gemrc'
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - bundle config path vendor/bundle
  - bundle install --jobs 4 --retry 3
  - bundle exec rails db:create db:schema:load db:test:prepare RAILS_ENV=test
  - bundle exec rspec --color --format documentation --require spec_helper --require rails_helper
notifications:
  email: false
