sudo: false
dist: xenial
language: ruby
rvm:
  - 2.6.5
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - bundle install --binstubs
  - ./bin/rails db:migrate RAILS_ENV=test
  - ./bin/rspec spec
notifications:
  email: false
