sudo: false
dist: xenial
language: ruby
rvm:
  - 2.6.5
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - bundle config path vendor/bundle
  - bundle install --jobs 4 --retry 3
  - bundle exec rails db:setup db:test:prepare RAILS_ENV=test
  - bundle exec rspec spec
notifications:
  email: false
