name: Ruby
on: [push]
jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@master

      - name: Setup Source
        run: |
          gem update --system
          gem install bundler
          bundle install
          rspec spec
